name: CI for Android App

# Controls when the workflow will run
# Triggers the workflow on push or pull request events on all branches
on:
  push:
    branches:
      - main
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code from the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Print Gradle version
        run: ./gradlew --version

      - name: Slack Notification
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: "https://hooks.slack.com/services/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"
        if: always()
